### PR TITLE
ci: create simple E2E test for github actions

### LINKED ISSUE #58: Set up E2E test with continuous integration
Hi @drewjbeh! Sorry for the flurry of PRs -- we have collaborators wanting to use our pipeline which depends on your tool, and so I'm hoping to help fix the breaking changes that have occurred recently.

Do you have interest in setting up a testing framework with continuous integration? If so, I'm happy to help do that. Getting this setup would allow you to detect when breaking changes occur and prevent bad PRs from being merged in the first place.

Let me know, thanks!

### PR DESCRIPTION
**Pull request by kelly-sovacool**
Resolves #58 

- [x] create GitHub Action to install the dev version and test it with pytest
- [x] create a simple test that runs the example test dataset
  - [x] test that the exit code is zero
  - [x] test that the md5sums of the output files match previous runs 
  - [x] repeat above for test without local modomics flag

### CODE REVIEW

**Comment by drewjbeh** [comment]
Thanks @kelly-sovacool. Fixed #59 so ready for testing. Bear in mind the MODOMICS folks are still trying to update the API. As of this morning it seems like some things are fixed but still remaining issues. This will impact E2E testing without the `--local-modomics' option. Really hoping these last creases are ironed out soon and then a full test will be possible

**Comment by kelly-sovacool** [comment]
@drewjbeh To speed up test runs, I created a subset of the example dataset using the first 1,000 sequences from each fastq file. Do you have suggestions for how to tweak the CLI arguments to further speed up the tests?

**Comment by drewjbeh** [comment]
@kelly-sovacool 1000 might be too few so watch out for weird errors. What I didn't take care of when writing mimseq, for example, are the errors that get thrown because of operations on empty/sparse tables. This was always a good way to QC the dataset in fact and helped us help others improve their library generation etc. 
The 4 fastq files for the test run are already subsets of the original, but I get the desire to speed up the tests even more

**Comment by kelly-sovacool** [comment]
Good news! The overall job is failing due to the test with the default modomics db, but the test passed successfully when using `--local-modomics`. I added checks for stable md5sums of several key output files. The runtime of the action is reasonable, less than 20 minutes. You can see the log from one of the GitHub Actions runs within my fork here: https://github.com/CCBR/mim-tRNAseq/actions/runs/6804330992/job/18501614841

@drewjbeh, could you take a look at the [list of files](https://github.com/CCBR/mim-tRNAseq/blob/ci-build-test/tests/md5sums.yml) I chose to check md5sums and let me know if you think there are additional ones we should add to make sure the test captures the most important functionality of mimseq? We'll just want to avoid ones that are likely to have unstable md5sums, e.g. BAM files.

**Comment by drewjbeh** [comment]
Great, just had a look through the commits. Looking good. Thanks again for your efforts. More good news is that the MODOMICS issues are also almost completely solved. I will let you know once they are and we can check if the default test finishes.

In terms of other outputs to check, I would add `mods/mismatchTable.csv` and perhaps also `mods_logOR/K562vsHEK293T_logOR.csv`

**Comment by drewjbeh** [comment]
@kelly-sovacool MODOMICS is finally working again. I have pushed a new version of mimseq (v1.3.8) to PyPi and Bioconda (and of course here as well). It might be a few days until the new version is available on bioconda.

**Comment by kelly-sovacool** [comment]
Great, I'll add md5sums for the test with the online modomics db!

**Comment by drewjbeh** [comment]
@kelly-sovacool looking good - ready to merge?

**Comment by kelly-sovacool** [comment]
@drewjbeh the tests with `--local-modomics` are failing because the md5sums changed. I didn't think there were any changes to mimseq in the last couple of weeks that would cause the output to change with local modomics. Do you know what could be causing this?

**Comment by drewjbeh** [comment]
Hmm not sure. Does the CI pull/build mimseq through conda? If so then it might be pulling the newest release and then there might be some changes indeed. Perhaps easiest is to regenerate the test set and md5s and rerun.

**Comment by kelly-sovacool** [comment]
It doesn't use mimseq via conda, it installs the latest version in the GitHub repo via pip, since the purpose is to test the current state of the codebase and catch bugs before they're merged/released. By the way, which commit corresponds to the release of v1.3.8?

**Comment by kelly-sovacool** [comment]
A new actions run is in progress here with the updated md5sums: https://github.com/CCBR/mim-tRNAseq/actions/runs/6947278085

If it's successful I'd say this is good to go.

**Comment by drewjbeh** [comment]
> It doesn't use mimseq via conda, it installs the latest version in the GitHub repo via pip, since the purpose is to test the current state of the codebase and catch bugs before they're merged/released. By the way, which commit corresponds to the release of v1.3.8?

Right, of course, sorry. 
The most recent commit is v1.3.8 (e65b0ba)

**Comment by kelly-sovacool** [comment]
No worries! I missed an md5sum, but I think this next run will likely completely successfully.

**Comment by drewjbeh** [comment]
@kelly-sovacool looks like the last test still didn't complete properly?

**Comment by kelly-sovacool** [comment]
@drewjbeh Yeah it went back to the old md5sums, it seems like they might be toggling back and forth? Need to investigate further to figure out why that might happen.

**Comment by kelly-sovacool** [comment]
@drewjbeh Do you have any ideas why the md5sums might switch or suggestions to look into?

**Comment by drewjbeh** [comment]
No clue. These files should be identical from one run to the next, at least in context of the most recent updates. Then again MODOMICS has been changing stuff on their end and this certainly could make minor changes to most of the outputs. I would say if they went back to the original md5sums then let's go with those for the test for now. But in the future, any changes say to MODOMICS,  or other updates to the algorithm will break this again.

**Comment by kelly-sovacool** [comment]
I wouldn't expect the md5sums to change for the test with `--local-modomics`, since it's not using the online modomics database, so this is quite confusing.

FWIW the tests without `--local-modomics` appear to be stable. If my most recent commit fails the test, perhaps I'll just remove the local modomics test.

**Comment by drewjbeh** [comment]
Yeah not sure where the issue is with the offline mode. If the tests pass I would also recommend removing `--local-modomics` tests as these are/should be rare use-cases anyway. Let me know how the tests go and we can merge. Thanks again!

**Comment by kelly-sovacool** [comment]
If this passes we'll be good to go: https://github.com/CCBR/mim-tRNAseq/actions/runs/7465511823

**Comment by kelly-sovacool** [comment]
@drewjbeh this is ready now

**Pull request merged**
